[tox]
envlist = py38, py39
skip_missing_interpreters = True

[testenv]
deps = 
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_dev.txt

commands = 
    # Linting: critical errors will show; warnings won't fail the run
    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Type checking
    mypy --ignore-missing-imports src/

    # Tests
    pytest -v tests/unit/unit.py
    pytest -v tests/integration/int.py
