[tox]
envlist = py38, py39

[testenv]
deps = 
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_dev.txt

commands = 
    # Linting
    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Type checking
    mypy --ignore-missing-imports src/

    # Unit tests
    pytest -v tests/unit/unit.py

    # Integration tests
    pytest -v tests/integration/int.py
